// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hiritewzhsokvkioctfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhpcml0ZXd6aHNva3ZraW9jdGZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDk2NTksImV4cCI6MjA2ODUyNTY1OX0.xmoLO4LF1h58lRHjaIeNeAsUyrMnWdXwk5dFKMdOF8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});